<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="List">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:string"/>
                            <xs:element name="naslov" type="xs:string"/>
                            <xs:element name="opis" type="xs:string" minOccurs="0"/>
                            <xs:element name="plata" type="xs:decimal"/>
                            <xs:element name="agencijaId" type="xs:string" minOccurs="0"/>
                            <xs:element name="zahtevaneVestine" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="vestina">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="id" type="xs:string"/>
                                                    <xs:element name="naziv" type="xs:string" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="nivo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="POCETNI"/>
                                                    <xs:enumeration value="SREDNJI"/>
                                                    <xs:enumeration value="NAPREDNI"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="prioritet">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="NIZAK"/>
                                                    <xs:enumeration value="VISOK"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
